// A centralized place for all theme color definitions.

// This object maps theme IDs to their display names for the UI
export const themeNames = {
    '80s-neon': '80s Neon',
    'abyss': 'Abyss',
    'alabaster': 'Alabaster',
    'alien-tech': 'Alien Tech',
    'amethyst': 'Amethyst',
    'arctic-theme': 'Arctic',
    'asphalt': 'Asphalt',
    'atlantis': 'Atlantis',
    'atom-one-dark': 'Atom One Dark',
    'atom-one-light': 'Atom One Light',
    'autumn-harvest': 'Autumn Harvest',
    'ayu-mirage': 'Ayu Mirage',
    'biohazard': 'Biohazard',
    'birchwood': 'Birchwood',
    'black-hole': 'Black Hole',
    'blood-moon': 'Blood Moon',
    'blueberry': 'Blueberry',
    'bubblegum': 'Bubblegum',
    'buttercup': 'Buttercup',
    'carbon-fiber': 'Carbon Fiber',
    'catppuccin-latte': 'Catppuccin Latte',
    'catppuccin-mocha': 'Catppuccin Mocha',
    'charcoal': 'Charcoal',
    'cherry-blossom': 'Cherry Blossom',
    'chocolate': 'Chocolate',
    'cinder': 'Cinder',
    'clay': 'Clay',
    'cloudy-sky': 'Cloudy Sky',
    'cobalt2': 'Cobalt2',
    'coffee-theme': 'Coffee',
    'community-material': 'Community Material',
    'coral-reef': 'Coral Reef',
    'cotton-candy': 'Cotton Candy',
    'cyberpunk': 'Cyberpunk',
    'dark-matter': 'Dark Matter',
    'daybreak': 'Daybreak',
    'deep-forest': 'Deep Forest',
    'deep-sea': 'Deep Sea',
    'deep-space': 'Deep Space',
    'dark': 'Default Dark',
    'light': 'Default Light',
    'desert-theme': 'Desert',
    'dracula': 'Dracula',
    'dracula-plus': 'Dracula+',
    'dungeon': 'Dungeon',
    'eclipse': 'Eclipse',
    'elvenwood': 'Elvenwood',
    'everforest-dark': 'Everforest Dark',
    'forest': 'Forest',
    'fresh-mint': 'Fresh Mint',
    'galactic': 'Galactic',
    'github-dark': 'GitHub Dark',
    'github-light': 'GitHub Light',
    'glacier': 'Glacier',
    'gothic-noir': 'Gothic Noir',
    'graphite': 'Graphite',
    'gruvbox-dark': 'Gruvbox Dark',
    'gruvbox-light': 'Gruvbox Light',
    'high-contrast': 'High Contrast',
    'holographic': 'Holographic',
    'ice-cream': 'Ice Cream',
    'inkwell': 'Inkwell',
    'jade': 'Jade',
    'jungle-theme': 'Jungle',
    'kimbie-dark': 'Kimbie Dark',
    'laserwave': 'Laserwave',
    'lavender-bliss': 'Lavender Bliss',
    'lemonade': 'Lemonade',
    'linen': 'Linen',
    'lucario': 'Lucario',
    'material-dark': 'Material Dark',
    'material-light': 'Material Light',
    'matcha': 'Matcha',
    'matrix': 'Matrix',
    'midnight-blue': 'Midnight Blue',
    'midnight-city': 'Midnight City',
    'mint-theme': 'Mint',
    'misty-morning': 'Misty Morning',
    'monokai': 'Monokai',
    'monokai-pro': 'Monokai Pro',
    'navy': 'Navy',
    'night-owl': 'Night Owl',
    'nocturne': 'Nocturne',
    'nord': 'Nord',
    'nord-deep': 'Nord Deep',
    'obsidian': 'Obsidian',
    'ocean': 'Ocean',
    'oil-slick': 'Oil Slick',
    'one-dark-pro': 'One Dark Pro',
    'outrun': 'Outrun',
    'palenight': 'Palenight',
    'panda-syntax': 'Panda Syntax',
    'paper-white': 'Paper White',
    'parchment': 'Parchment',
    'peach-sorbet': 'Peach Sorbet',
    'phantom': 'Phantom',
    'porcelain': 'Porcelain',
    'quiet-light': 'Quiet Light',
    'raven': 'Raven',
    'red-theme': 'Red',
    'retro-theme': 'Retro',
    'rose-pine': 'Rosé Pine',
    'ruby': 'Ruby',
    'sakura': 'Sakura',
    'savannah': 'Savannah',
    'seashell': 'Seashell',
    'shades-of-purple': 'Shades of Purple',
    'shadowlands': 'Shadowlands',
    'slate': 'Slate',
    'solarized-dark': 'Solarized Dark',
    'solarized-dark-plus': 'Solarized Dark+',
    'solarized-light': 'Solarized Light',
    'solarized-light-plus': 'Solarized Light+',
    'spring-meadow': 'Spring Meadow',
    'starless-night': 'Starless Night',
    'steampunk': 'Steampunk',
    'summer-sky': 'Summer Sky',
    'sunset': 'Sunset',
    'synthwave': 'Synthwave',
    'tokyo-night': 'Tokyo Night',
    'tomorrow-night-blue': 'Tomorrow Night Blue',
    'tropical': 'Tropical',
    'tundra': 'Tundra',
    'vanilla-cream': 'Vanilla Cream',
    'vaporwave': 'Vaporwave',
    'volcanic-ash': 'Volcanic Ash',
    'volcano': 'Volcano',
    'wine': 'Wine',
    'winter-is-coming-blue': 'Winter is Coming (Blue)',
    'winter-is-coming-dark': 'Winter is Coming (Dark)',
    'winter-is-coming-light': 'Winter is Coming (Light)',
    'witchcraft': 'Witchcraft',
};

// This object contains the color definitions for each theme
export const themeColors = {
    '80s-neon': {
        '--bg-primary': '#000000',
        '--bg-secondary': '#101010',
        '--bg-tertiary': '#202020',
        '--border-color': '#303030',
        '--text-primary': '#FF00FF',
        '--text-secondary': '#00FFFF',
        '--accent-primary': '#FFFF00',
        '--accent-hover': '#cccc00',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF0000',
        '--danger-hover': '#cc0000',
    },
    'abyss': {
        '--bg-primary': '#000c18',
        '--bg-secondary': '#001021',
        '--bg-tertiary': '#001f3f',
        '--border-color': '#003366',
        '--text-primary': '#6699cc',
        '--text-secondary': '#336699',
        '--accent-primary': '#33ccff',
        '--accent-hover': '#29a3cc',
        '--accent-text-color': '#000c18',
        '--danger-primary': '#cc3333',
        '--danger-hover': '#a32929',
    },
    'alabaster': {
        '--bg-primary': '#FCFCFC',
        '--bg-secondary': '#F4F4F4',
        '--bg-tertiary': '#ECECEC',
        '--border-color': '#E0E0E0',
        '--text-primary': '#333333',
        '--text-secondary': '#666666',
        '--accent-primary': '#B0B0B0',
        '--accent-hover': '#9E9E9E',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#C0C0C0',
        '--danger-hover': '#A9A9A9',
    },
    'alien-tech': {
        '--bg-primary': '#101D1A',
        '--bg-secondary': '#1A2D2A',
        '--bg-tertiary': '#243D3A',
        '--border-color': '#355852',
        '--text-primary': '#A7FFEB',
        '--text-secondary': '#64FFDA',
        '--accent-primary': '#1DE9B6',
        '--accent-hover': '#00BFA5',
        '--accent-text-color': '#101D1A',
        '--danger-primary': '#FF5252',
        '--danger-hover': '#D50000',
    },
    'amethyst': {
        '--bg-primary': '#2C243B',
        '--bg-secondary': '#3E3552',
        '--bg-tertiary': '#4F4668',
        '--border-color': '#655A82',
        '--text-primary': '#E1D8F0',
        '--text-secondary': '#B8A9D4',
        '--accent-primary': '#9D7AD4',
        '--accent-hover': '#8A69BF',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#D47A7A',
        '--danger-hover': '#BF6969',
    },
    'arctic-theme': {
        '--bg-primary': '#F8F9FA',
        '--bg-secondary': '#E9ECEF',
        '--bg-tertiary': '#DEE2E6',
        '--border-color': '#CED4DA',
        '--text-primary': '#212529',
        '--text-secondary': '#495057',
        '--accent-primary': '#007BFF',
        '--accent-hover': '#0062cc',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#DC3545',
        '--danger-hover': '#c82333',
    },
    'asphalt': {
        '--bg-primary': '#222222',
        '--bg-secondary': '#333333',
        '--bg-tertiary': '#444444',
        '--border-color': '#555555',
        '--text-primary': '#FFFFFF',
        '--text-secondary': '#E0E0E0',
        '--accent-primary': '#FFEB3B',
        '--accent-hover': '#FDD835',
        '--accent-text-color': '#000000',
        '--danger-primary': '#F44336',
        '--danger-hover': '#D32F2F',
    },
    'atlantis': {
        '--bg-primary': '#0A2E36',
        '--bg-secondary': '#10454F',
        '--bg-tertiary': '#165C6A',
        '--border-color': '#1E7385',
        '--text-primary': '#C2F2D0',
        '--text-secondary': '#8ED5A2',
        '--accent-primary': '#FFD700',
        '--accent-hover': '#E6C200',
        '--accent-text-color': '#0A2E36',
        '--danger-primary': '#FF6B6B',
        '--danger-hover': '#E65252',
    },
    'atom-one-dark': {
        '--bg-primary': '#282C34',
        '--bg-secondary': '#21252B',
        '--bg-tertiary': '#3A3F4B',
        '--border-color': '#181A1F',
        '--text-primary': '#ABB2BF',
        '--text-secondary': '#5C6370',
        '--accent-primary': '#61AFEF',
        '--accent-hover': '#4d8ccb',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E06C75',
        '--danger-hover': '#b3565d',
    },
    'atom-one-light': {
        '--bg-primary': '#FAFAFA',
        '--bg-secondary': '#F0F0F1',
        '--bg-tertiary': '#E5E5E6',
        '--border-color': '#D4D4D5',
        '--text-primary': '#383A42',
        '--text-secondary': '#696C77',
        '--accent-primary': '#4078F2',
        '--accent-hover': '#3360c1',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E45649',
        '--danger-hover': '#b6443a',
    },
    'autumn-harvest': {
        '--bg-primary': '#4D2C1B',
        '--bg-secondary': '#6B4226',
        '--bg-tertiary': '#895831',
        '--border-color': '#A76E3C',
        '--text-primary': '#F5EFE6',
        '--text-secondary': '#E4D8C9',
        '--accent-primary': '#D95F18',
        '--accent-hover': '#B84F14',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#C23B22',
        '--danger-hover': '#A1311C',
    },
    'ayu-mirage': {
        '--bg-primary': '#1f2430',
        '--bg-secondary': '#242936',
        '--bg-tertiary': '#575f6d',
        '--border-color': '#3e4451',
        '--text-primary': '#cbccc6',
        '--text-secondary': '#707a8c',
        '--accent-primary': '#ffad66',
        '--accent-hover': '#e69b5c',
        '--accent-text-color': '#1f2430',
        '--danger-primary': '#f07178',
        '--danger-hover': '#d8656b',
    },
    'biohazard': {
        '--bg-primary': '#1A221F',
        '--bg-secondary': '#24302A',
        '--bg-tertiary': '#2E3E35',
        '--border-color': '#425A4C',
        '--text-primary': '#C8E6C9',
        '--text-secondary': '#A5D6A7',
        '--accent-primary': '#FFF176',
        '--accent-hover': '#FFEE58',
        '--accent-text-color': '#1A221F',
        '--danger-primary': '#EF5350',
        '--danger-hover': '#D32F2F',
    },
    'birchwood': {
        '--bg-primary': '#F5F5DC',
        '--bg-secondary': '#E9E9D0',
        '--bg-tertiary': '#DDDDDD',
        '--border-color': '#C8C8B8',
        '--text-primary': '#5D564A',
        '--text-secondary': '#8B7D6B',
        '--accent-primary': '#A0522D',
        '--accent-hover': '#8B4513',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#CD5C5C',
        '--danger-hover': '#BC4A4A',
    },
    'black-hole': {
        '--bg-primary': '#010101',
        '--bg-secondary': '#0a0a0a',
        '--bg-tertiary': '#1a1a1a',
        '--border-color': '#2a2a2a',
        '--text-primary': '#e0e0e0',
        '--text-secondary': '#a0a0a0',
        '--accent-primary': '#7b42f5',
        '--accent-hover': '#6a37d4',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#e53935',
        '--danger-hover': '#c62828',
    },
    'blood-moon': {
        '--bg-primary': '#1A0000',
        '--bg-secondary': '#2E0000',
        '--bg-tertiary': '#4D0000',
        '--border-color': '#660000',
        '--text-primary': '#FFCCCC',
        '--text-secondary': '#FF8080',
        '--accent-primary': '#FF4D4D',
        '--accent-hover': '#e64545',
        '--accent-text-color': '#1A0000',
        '--danger-primary': '#FF0000',
        '--danger-hover': '#cc0000',
    },
    'blueberry': {
        '--bg-primary': '#1C233F',
        '--bg-secondary': '#2A345B',
        '--bg-tertiary': '#384577',
        '--border-color': '#465693',
        '--text-primary': '#D0D8F0',
        '--text-secondary': '#A8B3D9',
        '--accent-primary': '#6A8DCD',
        '--accent-hover': '#587AB8',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#CD6A6A',
        '--danger-hover': '#B85858',
    },
    'bubblegum': {
        '--bg-primary': '#FFDFE5',
        '--bg-secondary': '#FFE9EC',
        '--bg-tertiary': '#FCDCE0',
        '--border-color': '#F9CED5',
        '--text-primary': '#8B004B',
        '--text-secondary': '#C71585',
        '--accent-primary': '#4FC3F7',
        '--accent-hover': '#29B6F6',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF69B4',
        '--danger-hover': '#FF1493',
    },
    'buttercup': {
        '--bg-primary': '#FFF4BD',
        '--bg-secondary': '#FFEFAC',
        '--bg-tertiary': '#FFEAA0',
        '--border-color': '#FFDF80',
        '--text-primary': '#B8860B',
        '--text-secondary': '#DAA520',
        '--accent-primary': '#FFC107',
        '--accent-hover': '#FFB300',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF9800',
        '--danger-hover': '#FB8C00',
    },
    'carbon-fiber': {
        '--bg-primary': '#1A1A1A',
        '--bg-secondary': '#282828',
        '--bg-tertiary': '#363636',
        '--border-color': '#454545',
        '--text-primary': '#EAEAEA',
        '--text-secondary': '#BDBDBD',
        '--accent-primary': '#757575',
        '--accent-hover': '#616161',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#BDBDBD',
        '--danger-hover': '#9E9E9E',
    },
    'catppuccin-latte': {
        '--bg-primary': '#eff1f5',
        '--bg-secondary': '#e6e9ef',
        '--bg-tertiary': '#ccd0da',
        '--border-color': '#bcc0cc',
        '--text-primary': '#4c4f69',
        '--text-secondary': '#5c5f77',
        '--accent-primary': '#1e66f5',
        '--accent-hover': '#1852c4',
        '--accent-text-color': '#eff1f5',
        '--danger-primary': '#d20f39',
        '--danger-hover': '#a80c2e',
    },
    'catppuccin-mocha': {
        '--bg-primary': '#1e1e2e',
        '--bg-secondary': '#181825',
        '--bg-tertiary': '#313244',
        '--border-color': '#45475a',
        '--text-primary': '#cdd6f4',
        '--text-secondary': '#a6adc8',
        '--accent-primary': '#89b4fa',
        '--accent-hover': '#6d98e8',
        '--accent-text-color': '#1e1e2e',
        '--danger-primary': '#f38ba8',
        '--danger-hover': '#d87995',
    },
    'charcoal': {
        '--bg-primary': '#1E1E1E',
        '--bg-secondary': '#282828',
        '--bg-tertiary': '#3C3C3C',
        '--border-color': '#505050',
        '--text-primary': '#D1D1D1',
        '--text-secondary': '#A0A0A0',
        '--accent-primary': '#5A86AD',
        '--accent-hover': '#4A7092',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#AD5A5A',
        '--danger-hover': '#924A4A',
    },
    'cherry-blossom': {
        '--bg-primary': '#FFEFEF',
        '--bg-secondary': '#FFE5E5',
        '--bg-tertiary': '#FFDBDB',
        '--border-color': '#FFCACA',
        '--text-primary': '#8B0000',
        '--text-secondary': '#A52A2A',
        '--accent-primary': '#FFB6C1',
        '--accent-hover': '#FF69B4',
        '--accent-text-color': '#8B0000',
        '--danger-primary': '#F08080',
        '--danger-hover': '#CD5C5C',
    },
    'chocolate': {
        '--bg-primary': '#3E2723',
        '--bg-secondary': '#4E342E',
        '--bg-tertiary': '#5D4037',
        '--border-color': '#6D4C41',
        '--text-primary': '#D7CCC8',
        '--text-secondary': '#BCAAA4',
        '--accent-primary': '#A1887F',
        '--accent-hover': '#8D6E63',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#8D6E63',
        '--danger-hover': '#795548',
    },
    'cinder': {
        '--bg-primary': '#1E1B18',
        '--bg-secondary': '#2A2622',
        '--bg-tertiary': '#38322E',
        '--border-color': '#4F4842',
        '--text-primary': '#FFCCBC',
        '--text-secondary': '#FFAB91',
        '--accent-primary': '#FF7043',
        '--accent-hover': '#F4511E',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E64A19',
        '--danger-hover': '#D84315',
    },
    'clay': {
        '--bg-primary': '#BF7E65',
        '--bg-secondary': '#A66A53',
        '--bg-tertiary': '#8C5641',
        '--border-color': '#73422F',
        '--text-primary': '#F2EBE9',
        '--text-secondary': '#E4D9D5',
        '--accent-primary': '#734838',
        '--accent-hover': '#59382B',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#A65353',
        '--danger-hover': '#8C4141',
    },
    'cloudy-sky': {
        '--bg-primary': '#E8E9EB',
        '--bg-secondary': '#DFE1E3',
        '--bg-tertiary': '#D4D6D8',
        '--border-color': '#C5C7C9',
        '--text-primary': '#434C5E',
        '--text-secondary': '#5E6C84',
        '--accent-primary': '#81A1C1',
        '--accent-hover': '#5E81AC',
        '--accent-text-color': '#ECEFF4',
        '--danger-primary': '#BF616A',
        '--danger-hover': '#A55058',
    },
    'cobalt2': {
        '--bg-primary': '#193549',
        '--bg-secondary': '#21425d',
        '--bg-tertiary': '#2a5273',
        '--border-color': '#3b6e98',
        '--text-primary': '#e1efff',
        '--text-secondary': '#a5c8e6',
        '--accent-primary': '#ffc600',
        '--accent-hover': '#e6b200',
        '--accent-text-color': '#193549',
        '--danger-primary': '#ff3333',
        '--danger-hover': '#cc2929',
    },
    'coffee-theme': {
        '--bg-primary': '#302010',
        '--bg-secondary': '#403020',
        '--bg-tertiary': '#504030',
        '--border-color': '#605040',
        '--text-primary': '#E0D0C0',
        '--text-secondary': '#C0B0A0',
        '--accent-primary': '#A08060',
        '--accent-hover': '#80664d',
        '--accent-text-color': '#302010',
        '--danger-primary': '#C04040',
        '--danger-hover': '#993333',
    },
    'community-material': {
        '--bg-primary': '#263238',
        '--bg-secondary': '#2F3C43',
        '--bg-tertiary': '#37474F',
        '--border-color': '#455A64',
        '--text-primary': '#EEFFFF',
        '--text-secondary': '#B0BEC5',
        '--accent-primary': '#80CBC4',
        '--accent-hover': '#66a39e',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF5370',
        '--danger-hover': '#cc4259',
    },
    'coral-reef': {
        '--bg-primary': '#F0FFF0',
        '--bg-secondary': '#E0FFFF',
        '--bg-tertiary': '#D0FFFF',
        '--border-color': '#B0FFFF',
        '--text-primary': '#008B8B',
        '--text-secondary': '#20B2AA',
        '--accent-primary': '#FF7F50',
        '--accent-hover': '#FF6347',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF4500',
        '--danger-hover': '#E04000',
    },
    'cotton-candy': {
        '--bg-primary': '#FADADD',
        '--bg-secondary': '#F8CFD3',
        '--bg-tertiary': '#F6C5C9',
        '--border-color': '#F0B4BA',
        '--text-primary': '#DB7093',
        '--text-secondary': '#C71585',
        '--accent-primary': '#87CEFA',
        '--accent-hover': '#00BFFF',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF69B4',
        '--danger-hover': '#FF1493',
    },
    'cyberpunk': {
        '--bg-primary': '#0c0c1c',
        '--bg-secondary': '#1a1a3a',
        '--bg-tertiary': '#2a2a5a',
        '--border-color': '#5a5aff',
        '--text-primary': '#00ff00',
        '--text-secondary': '#00ffff',
        '--accent-primary': '#ff00ff',
        '--accent-hover': '#cc00cc',
        '--accent-text-color': '#000000',
        '--danger-primary': '#ff0000',
        '--danger-hover': '#cc0000',
    },
    'dark-matter': {
        '--bg-primary': '#120C1F',
        '--bg-secondary': '#1E162F',
        '--bg-tertiary': '#2A203F',
        '--border-color': '#3C2F5A',
        '--text-primary': '#E0D9F4',
        '--text-secondary': '#A99DCE',
        '--accent-primary': '#9575CD',
        '--accent-hover': '#7E57C2',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#F06292',
        '--danger-hover': '#E91E63',
    },
    'daybreak': {
        '--bg-primary': '#FCE5D8',
        '--bg-secondary': '#FADBCB',
        '--bg-tertiary': '#F8D1BE',
        '--border-color': '#EFC0A9',
        '--text-primary': '#6D4C41',
        '--text-secondary': '#8D6E63',
        '--accent-primary': '#FF8A65',
        '--accent-hover': '#FF7043',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E57373',
        '--danger-hover': '#EF5350',
    },
    'deep-forest': {
        '--bg-primary': '#0A140A',
        '--bg-secondary': '#122312',
        '--bg-tertiary': '#1A321A',
        '--border-color': '#284B28',
        '--text-primary': '#BDECB6',
        '--text-secondary': '#82A87C',
        '--accent-primary': '#6AAB5D',
        '--accent-hover': '#54884A',
        '--accent-text-color': '#0A140A',
        '--danger-primary': '#C62828',
        '--danger-hover': '#B71C1C',
    },
    'deep-sea': {
        '--bg-primary': '#00203F',
        '--bg-secondary': '#00304F',
        '--bg-tertiary': '#00405F',
        '--border-color': '#00506F',
        '--text-primary': '#ADEFD1',
        '--text-secondary': '#80CBC4',
        '--accent-primary': '#ADEFD1',
        '--accent-hover': '#80CBC4',
        '--accent-text-color': '#00203F',
        '--danger-primary': '#F07178',
        '--danger-hover': '#D8656B',
    },
    'deep-space': {
        '--bg-primary': '#040408',
        '--bg-secondary': '#0c0c18',
        '--bg-tertiary': '#141424',
        '--border-color': '#2d2d3f',
        '--text-primary': '#c0c5ce',
        '--text-secondary': '#8f96a3',
        '--accent-primary': '#00aaff',
        '--accent-hover': '#0088cc',
        '--accent-text-color': '#040408',
        '--danger-primary': '#ff4444',
        '--danger-hover': '#cc3333',
    },
    'dark': {
        '--bg-primary': '#1a1a1a',
        '--bg-secondary': '#2c2c2c',
        '--bg-tertiary': '#404040',
        '--border-color': '#555',
        '--text-primary': '#ffffff',
        '--text-secondary': '#b3b3b3',
        '--accent-primary': '#1db954',
        '--accent-hover': '#1aa34a',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#dc3545',
        '--danger-hover': '#c82333',
    },
    'light': {
        '--bg-primary': '#ffffff',
        '--bg-secondary': '#f0f0f0',
        '--bg-tertiary': '#e0e0e0',
        '--border-color': '#ccc',
        '--text-primary': '#000000',
        '--text-secondary': '#555555',
        '--accent-primary': '#1db954',
        '--accent-hover': '#1aa34a',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#dc3545',
        '--danger-hover': '#c82333',
    },
    'desert-theme': {
        '--bg-primary': '#FADDAF',
        '--bg-secondary': '#F8D097',
        '--bg-tertiary': '#F0C080',
        '--border-color': '#E8B068',
        '--text-primary': '#604020',
        '--text-secondary': '#806040',
        '--accent-primary': '#C08040',
        '--accent-hover': '#996633',
        '--accent-text-color': '#FADDAF',
        '--danger-primary': '#A04020',
        '--danger-hover': '#803319',
    },
    'dracula': {
        '--bg-primary': '#282a36',
        '--bg-secondary': '#383a59',
        '--bg-tertiary': '#44475a',
        '--border-color': '#6272a4',
        '--text-primary': '#f8f8f2',
        '--text-secondary': '#bd93f9',
        '--accent-primary': '#50fa7b',
        '--accent-hover': '#40c862',
        '--accent-text-color': '#282a36',
        '--danger-primary': '#ff5555',
        '--danger-hover': '#cc4444',
    },
    'dracula-plus': {
        '--bg-primary': '#1E1F29',
        '--bg-secondary': '#282A36',
        '--bg-tertiary': '#44475A',
        '--border-color': '#6272A4',
        '--text-primary': '#F8F8F2',
        '--text-secondary': '#6272A4',
        '--accent-primary': '#FF79C6',
        '--accent-hover': '#cc609e',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF5555',
        '--danger-hover': '#cc4444',
    },
    'dungeon': {
        '--bg-primary': '#25211E',
        '--bg-secondary': '#352E2A',
        '--bg-tertiary': '#453B36',
        '--border-color': '#5A4F4A',
        '--text-primary': '#D7CCC8',
        '--text-secondary': '#BCAAA4',
        '--accent-primary': '#FFAB40',
        '--accent-hover': '#FF9100',
        '--accent-text-color': '#25211E',
        '--danger-primary': '#BF360C',
        '--danger-hover': '#A62F0A',
    },
    'eclipse': {
        '--bg-primary': '#1B1B1B',
        '--bg-secondary': '#2A2A2A',
        '--bg-tertiary': '#3C3C3C',
        '--border-color': '#555555',
        '--text-primary': '#FFE082',
        '--text-secondary': '#FFCA28',
        '--accent-primary': '#FFA000',
        '--accent-hover': '#FF8F00',
        '--accent-text-color': '#1B1B1B',
        '--danger-primary': '#F57C00',
        '--danger-hover': '#EF6C00',
    },
    'elvenwood': {
        '--bg-primary': '#354031',
        '--bg-secondary': '#495944',
        '--bg-tertiary': '#5D7258',
        '--border-color': '#718B6C',
        '--text-primary': '#E8E4D9',
        '--text-secondary': '#D1CCBF',
        '--accent-primary': '#C7A865',
        '--accent-hover': '#B0935A',
        '--accent-text-color': '#354031',
        '--danger-primary': '#B56565',
        '--danger-hover': '#9E5A5A',
    },
    'everforest-dark': {
        '--bg-primary': '#2f383e',
        '--bg-secondary': '#272e33',
        '--bg-tertiary': '#4a555b',
        '--border-color': '#5b676c',
        '--text-primary': '#d3c6aa',
        '--text-secondary': '#a7c080',
        '--accent-primary': '#83c092',
        '--accent-hover': '#6da079',
        '--accent-text-color': '#2f383e',
        '--danger-primary': '#e67e80',
        '--danger-hover': '#c46b6d',
    },
    'forest': {
        '--bg-primary': '#2a3d2a',
        '--bg-secondary': '#3d5a3d',
        '--bg-tertiary': '#5a8a5a',
        '--border-color': '#8fbc8f',
        '--text-primary': '#e0e0e0',
        '--text-secondary': '#c0c0c0',
        '--accent-primary': '#a0d4a0',
        '--accent-hover': '#80a980',
        '--accent-text-color': '#2a3d2a',
        '--danger-primary': '#d4a0a0',
        '--danger-hover': '#aa8080',
    },
    'fresh-mint': {
        '--bg-primary': '#F0FFF0',
        '--bg-secondary': '#E0FFE0',
        '--bg-tertiary': '#D0FFD0',
        '--border-color': '#B8E8B8',
        '--text-primary': '#006400',
        '--text-secondary': '#2E8B57',
        '--accent-primary': '#3CB371',
        '--accent-hover': '#2E8B57',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF6347',
        '--danger-hover': '#E55337',
    },
    'galactic': {
        '--bg-primary': '#0C0A1D',
        '--bg-secondary': '#181433',
        '--bg-tertiary': '#241E49',
        '--border-color': '#30285F',
        '--text-primary': '#EAE8FF',
        '--text-secondary': '#D1CCFF',
        '--accent-primary': '#A77DFF',
        '--accent-hover': '#9168E6',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF7D7D',
        '--danger-hover': '#E66868',
    },
    'github-dark': {
        '--bg-primary': '#0d1117',
        '--bg-secondary': '#161b22',
        '--bg-tertiary': '#21262d',
        '--border-color': '#30363d',
        '--text-primary': '#c9d1d9',
        '--text-secondary': '#8b949e',
        '--accent-primary': '#58a6ff',
        '--accent-hover': '#4684cc',
        '--accent-text-color': '#0d1117',
        '--danger-primary': '#f85149',
        '--danger-hover': '#d4443d',
    },
    'github-light': {
        '--bg-primary': '#ffffff',
        '--bg-secondary': '#f6f8fa',
        '--bg-tertiary': '#e1e4e8',
        '--border-color': '#d0d7de',
        '--text-primary': '#24292f',
        '--text-secondary': '#57606a',
        '--accent-primary': '#0969da',
        '--accent-hover': '#0754b0',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#d73a49',
        '--danger-hover': '#b32d3a',
    },
    'glacier': {
        '--bg-primary': '#F0F8FF',
        '--bg-secondary': '#E6F2FF',
        '--bg-tertiary': '#DCEBFF',
        '--border-color': '#CADDFF',
        '--text-primary': '#4682B4',
        '--text-secondary': '#6495ED',
        '--accent-primary': '#87CEEB',
        '--accent-hover': '#87CEFA',
        '--accent-text-color': '#00008B',
        '--danger-primary': '#ADD8E6',
        '--danger-hover': '#87CEEB',
    },
    'gothic-noir': {
        '--bg-primary': '#100c0d',
        '--bg-secondary': '#1a1617',
        '--bg-tertiary': '#2c2627',
        '--border-color': '#4d4647',
        '--text-primary': '#e1e1e1',
        '--text-secondary': '#a1a1a1',
        '--accent-primary': '#9a0007',
        '--accent-hover': '#780005',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#c62828',
        '--danger-hover': '#a12020',
    },
    'graphite': {
        '--bg-primary': '#2E2E2E',
        '--bg-secondary': '#3C3C3C',
        '--bg-tertiary': '#4A4A4A',
        '--border-color': '#585858',
        '--text-primary': '#F5F5F5',
        '--text-secondary': '#E0E0E0',
        '--accent-primary': '#9E9E9E',
        '--accent-hover': '#757575',
        '--accent-text-color': '#2E2E2E',
        '--danger-primary': '#757575',
        '--danger-hover': '#616161',
    },
    'gruvbox-dark': {
        '--bg-primary': '#282828',
        '--bg-secondary': '#3c3836',
        '--bg-tertiary': '#504945',
        '--border-color': '#665c54',
        '--text-primary': '#ebdbb2',
        '--text-secondary': '#bdae93',
        '--accent-primary': '#fabd2f',
        '--accent-hover': '#c89725',
        '--accent-text-color': '#282828',
        '--danger-primary': '#fb4934',
        '--danger-hover': '#c93a29',
    },
    'gruvbox-light': {
        '--bg-primary': '#fbf1c7',
        '--bg-secondary': '#ebdbb2',
        '--bg-tertiary': '#d5c4a1',
        '--border-color': '#bdae93',
        '--text-primary': '#3c3836',
        '--text-secondary': '#504945',
        '--accent-primary': '#d65d0e',
        '--accent-hover': '#ab4a0b',
        '--accent-text-color': '#fbf1c7',
        '--danger-primary': '#cc241d',
        '--danger-hover': '#a31d17',
    },
    'high-contrast': {
        '--bg-primary': '#000000',
        '--bg-secondary': '#111111',
        '--bg-tertiary': '#222222',
        '--border-color': '#FFFFFF',
        '--text-primary': '#FFFFFF',
        '--text-secondary': '#E0E0E0',
        '--accent-primary': '#00FFFF',
        '--accent-hover': '#00cccc',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF0000',
        '--danger-hover': '#cc0000',
    },
    'holographic': {
        '--bg-primary': '#EAEAEA',
        '--bg-secondary': '#F0F0F0',
        '--bg-tertiary': '#F5F5F5',
        '--border-color': '#DCDCDC',
        '--text-primary': '#4A4A4A',
        '--text-secondary': '#7A7A7A',
        '--accent-primary': '#B27BFF',
        '--accent-hover': '#9D5CFF',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF7B7B',
        '--danger-hover': '#FF5C5C',
    },
    'ice-cream': {
        '--bg-primary': '#FDF5E6',
        '--bg-secondary': '#FFFACD',
        '--bg-tertiary': '#FAFAD2',
        '--border-color': '#EEE8AA',
        '--text-primary': '#6B8E23',
        '--text-secondary': '#808000',
        '--accent-primary': '#FFB6C1',
        '--accent-hover': '#FF69B4',
        '--accent-text-color': '#8B008B',
        '--danger-primary': '#FF7F50',
        '--danger-hover': '#FF6347',
    },
    'inkwell': {
        '--bg-primary': '#0F172A',
        '--bg-secondary': '#1E293B',
        '--bg-tertiary': '#334155',
        '--border-color': '#475569',
        '--text-primary': '#E2E8F0',
        '--text-secondary': '#94A3B8',
        '--accent-primary': '#38BDF8',
        '--accent-hover': '#0EA5E9',
        '--accent-text-color': '#0F172A',
        '--danger-primary': '#F43F5E',
        '--danger-hover': '#E11D48',
    },
    'jade': {
        '--bg-primary': '#2A3D39',
        '--bg-secondary': '#38524C',
        '--bg-tertiary': '#46675F',
        '--border-color': '#547C72',
        '--text-primary': '#E0EBE8',
        '--text-secondary': '#C2D4CF',
        '--accent-primary': '#50C878',
        '--accent-hover': '#45B36A',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#C85050',
        '--danger-hover': '#B34545',
    },
    'jungle-theme': {
        '--bg-primary': '#002A10',
        '--bg-secondary': '#004020',
        '--bg-tertiary': '#005A30',
        '--border-color': '#007A40',
        '--text-primary': '#A0E0B0',
        '--text-secondary': '#80C090',
        '--accent-primary': '#60A070',
        '--accent-hover': '#4d8059',
        '--accent-text-color': '#002A10',
        '--danger-primary': '#C04040',
        '--danger-hover': '#993333',
    },
    'kimbie-dark': {
        '--bg-primary': '#221a0f',
        '--bg-secondary': '#362712',
        '--bg-tertiary': '#4d3816',
        '--border-color': '#735521',
        '--text-primary': '#d3af86',
        '--text-secondary': '#a57a44',
        '--accent-primary': '#f06431',
        '--accent-hover': '#c05027',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#882b00',
        '--danger-hover': '#6d2200',
    },
    'laserwave': {
        '--bg-primary': '#1D0F3B',
        '--bg-secondary': '#140A2A',
        '--bg-tertiary': '#2E1A5C',
        '--border-color': '#4E3294',
        '--text-primary': '#E0E0E0',
        '--text-secondary': '#FF4DE4',
        '--accent-primary': '#00E5FF',
        '--accent-hover': '#00b7cc',
        '--accent-text-color': '#1D0F3B',
        '--danger-primary': '#FF3366',
        '--danger-hover': '#cc2951',
    },
    'lavender-bliss': {
        '--bg-primary': '#E6E6FA',
        '--bg-secondary': '#DCDCF8',
        '--bg-tertiary': '#D2D2F6',
        '--border-color': '#C1C1E8',
        '--text-primary': '#483D8B',
        '--text-secondary': '#6A5ACD',
        '--accent-primary': '#9370DB',
        '--accent-hover': '#8A2BE2',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FFA07A',
        '--danger-hover': '#FF7F50',
    },
    'lemonade': {
        '--bg-primary': '#FFFACD',
        '--bg-secondary': '#FFF8DC',
        '--bg-tertiary': '#FFF5CC',
        '--border-color': '#FFEB99',
        '--text-primary': '#556B2F',
        '--text-secondary': '#6B8E23',
        '--accent-primary': '#ADFF2F',
        '--accent-hover': '#9ACD32',
        '--accent-text-color': '#006400',
        '--danger-primary': '#FFD700',
        '--danger-hover': '#DAA520',
    },
    'linen': {
        '--bg-primary': '#FAF0E6',
        '--bg-secondary': '#F2E8DC',
        '--bg-tertiary': '#EAE0D2',
        '--border-color': '#DCD0C0',
        '--text-primary': '#5D4037',
        '--text-secondary': '#795548',
        '--accent-primary': '#A1887F',
        '--accent-hover': '#8D6E63',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#BCAAA4',
        '--danger-hover': '#A1887F',
    },
    'lucario': {
        '--bg-primary': '#2B3E50',
        '--bg-secondary': '#1F2C39',
        '--bg-tertiary': '#3F5E79',
        '--border-color': '#527aa1',
        '--text-primary': '#F8F8F2',
        '--text-secondary': '#A8A8A2',
        '--accent-primary': '#F8F8F2',
        '--accent-hover': '#c6c6c1',
        '--accent-text-color': '#2B3E50',
        '--danger-primary': '#E84F4F',
        '--danger-hover': '#b93f3f',
    },
    'material-dark': {
        '--bg-primary': '#121212',
        '--bg-secondary': '#1E1E1E',
        '--bg-tertiary': '#2C2C2C',
        '--border-color': '#3A3A3A',
        '--text-primary': '#FFFFFF',
        '--text-secondary': '#B0B0B0',
        '--accent-primary': '#BB86FC',
        '--accent-hover': '#9e67e3',
        '--accent-text-color': '#000000',
        '--danger-primary': '#CF6679',
        '--danger-hover': '#b15665',
    },
    'material-light': {
        '--bg-primary': '#FFFFFF',
        '--bg-secondary': '#F5F5F5',
        '--bg-tertiary': '#E0E0E0',
        '--border-color': '#D1D1D1',
        '--text-primary': '#000000',
        '--text-secondary': '#616161',
        '--accent-primary': '#6200EE',
        '--accent-hover': '#3700B3',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#B00020',
        '--danger-hover': '#8c0019',
    },
    'matcha': {
        '--bg-primary': '#E8F5E9',
        '--bg-secondary': '#F1FAF1',
        '--bg-tertiary': '#D7EED9',
        '--border-color': '#C5E4C7',
        '--text-primary': '#385538',
        '--text-secondary': '#558B2F',
        '--accent-primary': '#81C784',
        '--accent-hover': '#66BB6A',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#EF9A9A',
        '--danger-hover': '#E57373',
    },
    'matrix': {
        '--bg-primary': '#000000',
        '--bg-secondary': '#0D0D0D',
        '--bg-tertiary': '#1A1A1A',
        '--border-color': '#222222',
        '--text-primary': '#00FF41',
        '--text-secondary': '#00b32d',
        '--accent-primary': '#00FF41',
        '--accent-hover': '#00cc34',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF0000',
        '--danger-hover': '#cc0000',
    },
    'midnight-blue': {
        '--bg-primary': '#00102A',
        '--bg-secondary': '#001C40',
        '--bg-tertiary': '#002B60',
        '--border-color': '#004080',
        '--text-primary': '#D0E0FF',
        '--text-secondary': '#80A0D0',
        '--accent-primary': '#60A0FF',
        '--accent-hover': '#4d80cc',
        '--accent-text-color': '#00102A',
        '--danger-primary': '#FF6060',
        '--danger-hover': '#cc4d4d',
    },
    'midnight-city': {
        '--bg-primary': '#0A0F2D',
        '--bg-secondary': '#141937',
        '--bg-tertiary': '#1E2341',
        '--border-color': '#2C314F',
        '--text-primary': '#E0E7FF',
        '--text-secondary': '#A5B4FC',
        '--accent-primary': '#EC4899',
        '--accent-hover': '#DB2777',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#F43F5E',
        '--danger-hover': '#BE123C',
    },
    'mint-theme': {
        '--bg-primary': '#F0FFF4',
        '--bg-secondary': '#E0F8E8',
        '--bg-tertiary': '#C0F0D0',
        '--border-color': '#A0E8B8',
        '--text-primary': '#004D20',
        '--text-secondary': '#006D30',
        '--accent-primary': '#008D40',
        '--accent-hover': '#007033',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#D04040',
        '--danger-hover': '#a63333',
    },
    'misty-morning': {
        '--bg-primary': '#E1E4E0',
        '--bg-secondary': '#D5D8D4',
        '--bg-tertiary': '#C9CCC8',
        '--border-color': '#B8BAB6',
        '--text-primary': '#3E4C59',
        '--text-secondary': '#5A6978',
        '--accent-primary': '#8FBCBB',
        '--accent-hover': '#81A1C1',
        '--accent-text-color': '#2E3440',
        '--danger-primary': '#BF616A',
        '--danger-hover': '#A35058',
    },
    'monokai': {
        '--bg-primary': '#272822',
        '--bg-secondary': '#3e3d32',
        '--bg-tertiary': '#75715e',
        '--border-color': '#999',
        '--text-primary': '#f8f8f2',
        '--text-secondary': '#a6e22e',
        '--accent-primary': '#f92672',
        '--accent-hover': '#c71e5b',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#f92672',
        '--danger-hover': '#c71e5b',
    },
    'monokai-pro': {
        '--bg-primary': '#2D2A2E',
        '--bg-secondary': '#221F22',
        '--bg-tertiary': '#403E41',
        '--border-color': '#535154',
        '--text-primary': '#FCFCFA',
        '--text-secondary': '#7F7980',
        '--accent-primary': '#FFD866',
        '--accent-hover': '#e6c25c',
        '--accent-text-color': '#2D2A2E',
        '--danger-primary': '#FF6188',
        '--danger-hover': '#cc4d6c',
    },
    'navy': {
        '--bg-primary': '#2C3E50',
        '--bg-secondary': '#34495E',
        '--bg-tertiary': '#4A637A',
        '--border-color': '#5E7A94',
        '--text-primary': '#ECF0F1',
        '--text-secondary': '#BDC3C7',
        '--accent-primary': '#BDC3C7',
        '--accent-hover': '#AAB1B5',
        '--accent-text-color': '#2C3E50',
        '--danger-primary': '#E74C3C',
        '--danger-hover': '#C0392B',
    },
    'night-owl': {
        '--bg-primary': '#011627',
        '--bg-secondary': '#011221',
        '--bg-tertiary': '#0b253a',
        '--border-color': '#1d3b53',
        '--text-primary': '#d6deeb',
        '--text-secondary': '#80a4c2',
        '--accent-primary': '#82aaff',
        '--accent-hover': '#6888cc',
        '--accent-text-color': '#011627',
        '--danger-primary': '#ef5350',
        '--danger-hover': '#d74a47',
    },
    'nocturne': {
        '--bg-primary': '#1E293B',
        '--bg-secondary': '#2B3A4E',
        '--bg-tertiary': '#3A4C63',
        '--border-color': '#4D617A',
        '--text-primary': '#CBD5E1',
        '--text-secondary': '#94A3B8',
        '--accent-primary': '#C0C0C0',
        '--accent-hover': '#A9A9A9',
        '--accent-text-color': '#1E293B',
        '--danger-primary': '#F87171',
        '--danger-hover': '#EF4444',
    },
    'nord': {
        '--bg-primary': '#2E3440',
        '--bg-secondary': '#3B4252',
        '--bg-tertiary': '#434C5E',
        '--border-color': '#4C566A',
        '--text-primary': '#ECEFF4',
        '--text-secondary': '#D8DEE9',
        '--accent-primary': '#88C0D0',
        '--accent-hover': '#6ca9bc',
        '--accent-text-color': '#2E3440',
        '--danger-primary': '#BF616A',
        '--danger-hover': '#a55058',
    },
    'nord-deep': {
        '--bg-primary': '#242933',
        '--bg-secondary': '#292E39',
        '--bg-tertiary': '#343A46',
        '--border-color': '#4C566A',
        '--text-primary': '#ECEFF4',
        '--text-secondary': '#D8DEE9',
        '--accent-primary': '#8FBCBB',
        '--accent-hover': '#81A1C1',
        '--accent-text-color': '#242933',
        '--danger-primary': '#BF616A',
        '--danger-hover': '#a55058',
    },
    'obsidian': {
        '--bg-primary': '#0B0B0E',
        '--bg-secondary': '#15151A',
        '--bg-tertiary': '#212126',
        '--border-color': '#333338',
        '--text-primary': '#E0E0E0',
        '--text-secondary': '#A0A0A0',
        '--accent-primary': '#00BCD4',
        '--accent-hover': '#0097A7',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#F44336',
        '--danger-hover': '#D32F2F',
    },
    'ocean': {
        '--bg-primary': '#003366',
        '--bg-secondary': '#004c99',
        '--bg-tertiary': '#0066cc',
        '--border-color': '#3399ff',
        '--text-primary': '#ffffff',
        '--text-secondary': '#e0e0e0',
        '--accent-primary': '#66ccff',
        '--accent-hover': '#51a3cc',
        '--accent-text-color': '#003366',
        '--danger-primary': '#ff6666',
        '--danger-hover': '#cc5151',
    },
    'oil-slick': {
        '--bg-primary': '#0F0F12',
        '--bg-secondary': '#1A1A1E',
        '--bg-tertiary': '#25252A',
        '--border-color': '#38383D',
        '--text-primary': '#C5CAE9',
        '--text-secondary': '#7986CB',
        '--accent-primary': '#4DB6AC',
        '--accent-hover': '#26A69A',
        '--accent-text-color': '#0F0F12',
        '--danger-primary': '#FF7043',
        '--danger-hover': '#F4511E',
    },
    'one-dark-pro': {
        '--bg-primary': '#282c34',
        '--bg-secondary': '#21252b',
        '--bg-tertiary': '#3a3f4b',
        '--border-color': '#4b5263',
        '--text-primary': '#abb2bf',
        '--text-secondary': '#828997',
        '--accent-primary': '#61afef',
        '--accent-hover': '#4d92c7',
        '--accent-text-color': '#282c34',
        '--danger-primary': '#e06c75',
        '--danger-hover': '#b85860',
    },
    'outrun': {
        '--bg-primary': '#1A1136',
        '--bg-secondary': '#100A20',
        '--bg-tertiary': '#2A1C54',
        '--border-color': '#4A3B84',
        '--text-primary': '#F0F0F0',
        '--text-secondary': '#FF79C6',
        '--accent-primary': '#66D9EF',
        '--accent-hover': '#51adbe',
        '--accent-text-color': '#1A1136',
        '--danger-primary': '#FF4365',
        '--danger-hover': '#d93955',
    },
    'palenight': {
        '--bg-primary': '#292D3E',
        '--bg-secondary': '#202331',
        '--bg-tertiary': '#444267',
        '--border-color': '#565f89',
        '--text-primary': '#A6ACCD',
        '--text-secondary': '#676E95',
        '--accent-primary': '#82AAFF',
        '--accent-hover': '#6888cc',
        '--accent-text-color': '#292D3E',
        '--danger-primary': '#F07178',
        '--danger-hover': '#d8656b',
    },
    'panda-syntax': {
        '--bg-primary': '#292A2B',
        '--bg-secondary': '#242526',
        '--bg-tertiary': '#343536',
        '--border-color': '#4f5051',
        '--text-primary': '#E6E6E6',
        '--text-secondary': '#B3B3B3',
        '--accent-primary': '#19F9D8',
        '--accent-hover': '#14c7ae',
        '--accent-text-color': '#000000',
        '--danger-primary': '#FF2C6D',
        '--danger-hover': '#cc2357',
    },
    'paper-white': {
        '--bg-primary': '#F8F8F8',
        '--bg-secondary': '#F0F0F0',
        '--bg-tertiary': '#E8E8E8',
        '--border-color': '#DCDCDC',
        '--text-primary': '#333333',
        '--text-secondary': '#555555',
        '--accent-primary': '#777777',
        '--accent-hover': '#666666',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#B22222',
        '--danger-hover': '#8B0000',
    },
    'parchment': {
        '--bg-primary': '#FDF5E6',
        '--bg-secondary': '#F5EDDC',
        '--bg-tertiary': '#EFE5D2',
        '--border-color': '#E8DBC8',
        '--text-primary': '#8B4513',
        '--text-secondary': '#A0522D',
        '--accent-primary': '#D2B48C',
        '--accent-hover': '#BC8F8F',
        '--accent-text-color': '#8B4513',
        '--danger-primary': '#A52A2A',
        '--danger-hover': '#800000',
    },
    'peach-sorbet': {
        '--bg-primary': '#FFDAB9',
        '--bg-secondary': '#FFD0A9',
        '--bg-tertiary': '#FFC699',
        '--border-color': '#FFB27F',
        '--text-primary': '#A0522D',
        '--text-secondary': '#8B4513',
        '--accent-primary': '#FFA07A',
        '--accent-hover': '#FF8C69',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E9967A',
        '--danger-hover': '#CD5C5C',
    },
    'phantom': {
        '--bg-primary': '#1D2228',
        '--bg-secondary': '#282E36',
        '--bg-tertiary': '#343A44',
        '--border-color': '#4A515B',
        '--text-primary': '#B0BEC5',
        '--text-secondary': '#78909C',
        '--accent-primary': '#607D8B',
        '--accent-hover': '#546E7A',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#9E9E9E',
        '--danger-hover': '#757575',
    },
    'porcelain': {
        '--bg-primary': '#F9F9F9',
        '--bg-secondary': '#F1F1F1',
        '--bg-tertiary': '#E9E9E9',
        '--border-color': '#DEDEDE',
        '--text-primary': '#4A4A4A',
        '--text-secondary': '#6A6A6A',
        '--accent-primary': '#ADD8E6',
        '--accent-hover': '#87CEEB',
        '--accent-text-color': '#4682B4',
        '--danger-primary': '#B0C4DE',
        '--danger-hover': '#778899',
    },
    'quiet-light': {
        '--bg-primary': '#F5F5F5',
        '--bg-secondary': '#EEEEEE',
        '--bg-tertiary': '#E0E0E0',
        '--border-color': '#D4D4D4',
        '--text-primary': '#333333',
        '--text-secondary': '#777777',
        '--accent-primary': '#4275A9',
        '--accent-hover': '#345d87',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#C93C3C',
        '--danger-hover': '#a13030',
    },
    'raven': {
        '--bg-primary': '#0C0C0E',
        '--bg-secondary': '#18181C',
        '--bg-tertiary': '#24242A',
        '--border-color': '#3A3A40',
        '--text-primary': '#D1C4E9',
        '--text-secondary': '#9575CD',
        '--accent-primary': '#7E57C2',
        '--accent-hover': '#5E35B1',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#EF5350',
        '--danger-hover': '#C62828',
    },
    'red-theme': {
        '--bg-primary': '#270000',
        '--bg-secondary': '#4d0000',
        '--bg-tertiary': '#6b0000',
        '--border-color': '#8e0000',
        '--text-primary': '#ffbaba',
        '--text-secondary': '#ff8a8a',
        '--accent-primary': '#ff5252',
        '--accent-hover': '#ff1f1f',
        '--accent-text-color': '#000000',
        '--danger-primary': '#ff1744',
        '--danger-hover': '#c4001d',
    },
    'retro-theme': {
        '--bg-primary': '#D6C6A8',
        '--bg-secondary': '#C8B898',
        '--bg-tertiary': '#B0A080',
        '--border-color': '#988868',
        '--text-primary': '#3A2A0A',
        '--text-secondary': '#5A4A2A',
        '--accent-primary': '#8A6A4A',
        '--accent-hover': '#6e543b',
        '--accent-text-color': '#D6C6A8',
        '--danger-primary': '#A04040',
        '--danger-hover': '#803333',
    },
    'rose-pine': {
        '--bg-primary': '#191724',
        '--bg-secondary': '#1f1d2e',
        '--bg-tertiary': '#26233a',
        '--border-color': '#403d52',
        '--text-primary': '#e0def4',
        '--text-secondary': '#908caa',
        '--accent-primary': '#eb6f92',
        '--accent-hover': '#bb5874',
        '--accent-text-color': '#191724',
        '--danger-primary': '#eb6f92',
        '--danger-hover': '#bb5874',
    },
    'ruby': {
        '--bg-primary': '#4C0000',
        '--bg-secondary': '#660000',
        '--bg-tertiary': '#800000',
        '--border-color': '#990000',
        '--text-primary': '#FFD9D9',
        '--text-secondary': '#FFB3B3',
        '--accent-primary': '#E0115F',
        '--accent-hover': '#C7004C',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#D21414',
        '--danger-hover': '#B81212',
    },
    'sakura': {
        '--bg-primary': '#FFF0F5',
        '--bg-secondary': '#FFE4E1',
        '--bg-tertiary': '#FFD8D1',
        '--border-color': '#FFC0CB',
        '--text-primary': '#C71585',
        '--text-secondary': '#DB7093',
        '--accent-primary': '#FF69B4',
        '--accent-hover': '#FF1493',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#DC143C',
        '--danger-hover': '#C31235',
    },
    'savannah': {
        '--bg-primary': '#EADCB3',
        '--bg-secondary': '#D8C49A',
        '--bg-tertiary': '#C6AC81',
        '--border-color': '#B49468',
        '--text-primary': '#594521',
        '--text-secondary': '#7A623E',
        '--accent-primary': '#708238',
        '--accent-hover': '#5E6F2F',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#A85C5C',
        '--danger-hover': '#8F4D4D',
    },
    'seashell': {
        '--bg-primary': '#FFF5EE',
        '--bg-secondary': '#F5EBE0',
        '--bg-tertiary': '#EFE1D6',
        '--border-color': '#E8D7CC',
        '--text-primary': '#A0522D',
        '--text-secondary': '#8B4513',
        '--accent-primary': '#F4A460',
        '--accent-hover': '#CD853F',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#E9967A',
        '--danger-hover': '#D2691E',
    },
    'shades-of-purple': {
        '--bg-primary': '#2d2b55',
        '--bg-secondary': '#222041',
        '--bg-tertiary': '#4d4b84',
        '--border-color': '#6c6783',
        '--text-primary': '#ffffff',
        '--text-secondary': '#a599e9',
        '--accent-primary': '#fad000',
        '--accent-hover': '#e1bb00',
        '--accent-text-color': '#2d2b55',
        '--danger-primary': '#d90429',
        '--danger-hover': '#b50322',
    },
    'shadowlands': {
        '--bg-primary': '#18151E',
        '--bg-secondary': '#24202C',
        '--bg-tertiary': '#302B3A',
        '--border-color': '#454050',
        '--text-primary': '#D8BFD8',
        '--text-secondary': '#B19CDA',
        '--accent-primary': '#9370DB',
        '--accent-hover': '#8A2BE2',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#CD5C5C',
        '--danger-hover': '#C14040',
    },
    'slate': {
        '--bg-primary': '#343D46',
        '--bg-secondary': '#4F5B66',
        '--bg-tertiary': '#6A7885',
        '--border-color': '#8493A1',
        '--text-primary': '#C0C5CE',
        '--text-secondary': '#A7B0B9',
        '--accent-primary': '#8A9AA8',
        '--accent-hover': '#7B8A97',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#A88A8A',
        '--danger-hover': '#977B7B',
    },
    'solarized-dark': {
        '--bg-primary': '#002b36',
        '--bg-secondary': '#073642',
        '--bg-tertiary': '#586e75',
        '--border-color': '#657b83',
        '--text-primary': '#839496',
        '--text-secondary': '#93a1a1',
        '--accent-primary': '#268bd2',
        '--accent-hover': '#1e6fa9',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#dc322f',
        '--danger-hover': '#b02825',
    },
    'solarized-dark-plus': {
        '--bg-primary': '#00252E',
        '--bg-secondary': '#003847',
        '--bg-tertiary': '#004F63',
        '--border-color': '#006C87',
        '--text-primary': '#839496',
        '--text-secondary': '#586E75',
        '--accent-primary': '#D33682',
        '--accent-hover': '#a92b68',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#DC322F',
        '--danger-hover': '#b02825',
    },
    'solarized-light': {
        '--bg-primary': '#fdf6e3',
        '--bg-secondary': '#eee8d5',
        '--bg-tertiary': '#93a1a1',
        '--border-color': '#839496',
        '--text-primary': '#657b83',
        '--text-secondary': '#586e75',
        '--accent-primary': '#268bd2',
        '--accent-hover': '#1e6fa9',
        '--accent-text-color': '#ffffff',
        '--danger-primary': '#dc322f',
        '--danger-hover': '#b02825',
    },
    'solarized-light-plus': {
        '--bg-primary': '#FEFBF1',
        '--bg-secondary': '#F5F0E0',
        '--bg-tertiary': '#E8E0C8',
        '--border-color': '#DCD0B0',
        '--text-primary': '#657B83',
        '--text-secondary': '#93A1A1',
        '--accent-primary': '#6C71C4',
        '--accent-hover': '#565aa3',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#DC322F',
        '--danger-hover': '#b02825',
    },
    'spring-meadow': {
        '--bg-primary': '#F0FFF0',
        '--bg-secondary': '#E6FEE6',
        '--bg-tertiary': '#DCFCDC',
        '--border-color': '#C8F8C8',
        '--text-primary': '#228B22',
        '--text-secondary': '#32CD32',
        '--accent-primary': '#ADFF2F',
        '--accent-hover': '#9ACD32',
        '--accent-text-color': '#228B22',
        '--danger-primary': '#FF7F50',
        '--danger-hover': '#FF6347',
    },
    'starless-night': {
        '--bg-primary': '#030509',
        '--bg-secondary': '#0b0d15',
        '--bg-tertiary': '#151823',
        '--border-color': '#2a2e3f',
        '--text-primary': '#d1d1d1',
        '--text-secondary': '#9e9e9e',
        '--accent-primary': '#a8b2c2',
        '--accent-hover': '#8e97a6',
        '--accent-text-color': '#030509',
        '--danger-primary': '#e57373',
        '--danger-hover': '#d32f2f',
    },
    'steampunk': {
        '--bg-primary': '#5A3E2B',
        '--bg-secondary': '#4B3321',
        '--bg-tertiary': '#6B523F',
        '--border-color': '#7C614D',
        '--text-primary': '#EAE0D5',
        '--text-secondary': '#D8CBBF',
        '--accent-primary': '#B08D57',
        '--accent-hover': '#9A7A4C',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#9A5757',
        '--danger-hover': '#834C4C',
    },
    'summer-sky': {
        '--bg-primary': '#F0F8FF',
        '--bg-secondary': '#E1F5FE',
        '--bg-tertiary': '#B3E5FC',
        '--border-color': '#81D4FA',
        '--text-primary': '#01579B',
        '--text-secondary': '#0288D1',
        '--accent-primary': '#03A9F4',
        '--accent-hover': '#039BE5',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FF9800',
        '--danger-hover': '#FB8C00',
    },
    'sunset': {
        '--bg-primary': '#4c1a3d',
        '--bg-secondary': '#662251',
        '--bg-tertiary': '#802b66',
        '--border-color': '#b33e8d',
        '--text-primary': '#ffcc99',
        '--text-secondary': '#ffddb3',
        '--accent-primary': '#ff9966',
        '--accent-hover': '#cc7a51',
        '--accent-text-color': '#4c1a3d',
        '--danger-primary': '#ff3333',
        '--danger-hover': '#cc2828',
    },
    'synthwave': {
        '--bg-primary': '#2b1055',
        '--bg-secondary': '#25214D',
        '--bg-tertiary': '#342964',
        '--border-color': '#5f43b2',
        '--text-primary': '#ffffff',
        '--text-secondary': '#f6edff',
        '--accent-primary': '#ff6ac1',
        '--accent-hover': '#cc549a',
        '--accent-text-color': '#2b1055',
        '--danger-primary': '#ff6961',
        '--danger-hover': '#cd544d',
    },
    'tokyo-night': {
        '--bg-primary': '#1a1b26',
        '--bg-secondary': '#24283b',
        '--bg-tertiary': '#414868',
        '--border-color': '#565f89',
        '--text-primary': '#c0caf5',
        '--text-secondary': '#a9b1d6',
        '--accent-primary': '#7aa2f7',
        '--accent-hover': '#5d83d9',
        '--accent-text-color': '#1a1b26',
        '--danger-primary': '#f7768e',
        '--danger-hover': '#d96278',
    },
    'tomorrow-night-blue': {
        '--bg-primary': '#002451',
        '--bg-secondary': '#00346E',
        '--bg-tertiary': '#004794',
        '--border-color': '#0059b8',
        '--text-primary': '#FFFFFF',
        '--text-secondary': '#A2B3C5',
        '--accent-primary': '#BBDAFF',
        '--accent-hover': '#95aed3',
        '--accent-text-color': '#002451',
        '--danger-primary': '#FF9DA4',
        '--danger-hover': '#cc7d83',
    },
    'tropical': {
        '--bg-primary': '#E0F7FA',
        '--bg-secondary': '#F0FDFF',
        '--bg-tertiary': '#B2EBF2',
        '--border-color': '#80DEEA',
        '--text-primary': '#004D40',
        '--text-secondary': '#00796B',
        '--accent-primary': '#FF7043',
        '--accent-hover': '#FF5722',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#FFAB40',
        '--danger-hover': '#FF9100',
    },
    'tundra': {
        '--bg-primary': '#E1E8ED',
        '--bg-secondary': '#CFD8DC',
        '--bg-tertiary': '#B0BEC5',
        '--border-color': '#90A4AE',
        '--text-primary': '#37474F',
        '--text-secondary': '#546E7A',
        '--accent-primary': '#607D8B',
        '--accent-hover': '#546E7A',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#816060',
        '--danger-hover': '#6F5454',
    },
    'vanilla-cream': {
        '--bg-primary': '#FDF5E6',
        '--bg-secondary': '#FAFAD2',
        '--bg-tertiary': '#F5F5DC',
        '--border-color': '#E8E8C8',
        '--text-primary': '#BDB76B',
        '--text-secondary': '#F0E68C',
        '--accent-primary': '#FFD700',
        '--accent-hover': '#DAA520',
        '--accent-text-color': '#8B4513',
        '--danger-primary': '#FFA07A',
        '--danger-hover': '#FF8C69',
    },
    'vaporwave': {
        '--bg-primary': '#0d0221',
        '--bg-secondary': '#261447',
        '--bg-tertiary': '#3a2466',
        '--border-color': '#5c4099',
        '--text-primary': '#f0f0f0',
        '--text-secondary': '#ff79c6',
        '--accent-primary': '#00f5d4',
        '--accent-hover': '#00c4a9',
        '--accent-text-color': '#0d0221',
        '--danger-primary': '#ff4365',
        '--danger-hover': '#d93955',
    },
    'volcanic-ash': {
        '--bg-primary': '#1C1C1C',
        '--bg-secondary': '#2B2B2B',
        '--bg-tertiary': '#3A3A3A',
        '--border-color': '#4E4E4E',
        '--text-primary': '#F5F5F5',
        '--text-secondary': '#BDBDBD',
        '--accent-primary': '#FF5722',
        '--accent-hover': '#E64A19',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#D32F2F',
        '--danger-hover': '#B71C1C',
    },
    'volcano': {
        '--bg-primary': '#1F1F1F',
        '--bg-secondary': '#2A2A2A',
        '--bg-tertiary': '#3B3B3B',
        '--border-color': '#4D4D4D',
        '--text-primary': '#E0E0E0',
        '--text-secondary': '#BDBDBD',
        '--accent-primary': '#FF4500',
        '--accent-hover': '#E63E00',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#D32F2F',
        '--danger-hover': '#B71C1C',
    },
    'wine': {
        '--bg-primary': '#4A001E',
        '--bg-secondary': '#600027',
        '--bg-tertiary': '#760030',
        '--border-color': '#8C0039',
        '--text-primary': '#F1E4E8',
        '--text-secondary': '#E3D0D6',
        '--accent-primary': '#C2185B',
        '--accent-hover': '#A3144D',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#AD1414',
        '--danger-hover': '#931111',
    },
    'winter-is-coming-blue': {
        '--bg-primary': '#021523',
        '--bg-secondary': '#01101C',
        '--bg-tertiary': '#0B253A',
        '--border-color': '#103A56',
        '--text-primary': '#D6DEEB',
        '--text-secondary': '#A2B3C5',
        '--accent-primary': '#3C8DBC',
        '--accent-hover': '#2f7096',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#EF5350',
        '--danger-hover': '#d74a47',
    },
    'winter-is-coming-dark': {
        '--bg-primary': '#011627',
        '--bg-secondary': '#011221',
        '--bg-tertiary': '#0B2942',
        '--border-color': '#103A56',
        '--text-primary': '#D6DEEB',
        '--text-secondary': '#A2B3C5',
        '--accent-primary': '#ADD8E6',
        '--accent-hover': '#8abecb',
        '--accent-text-color': '#011627',
        '--danger-primary': '#EF5350',
        '--danger-hover': '#d74a47',
    },
    'winter-is-coming-light': {
        '--bg-primary': '#FFFFFF',
        '--bg-secondary': '#EAEAEA',
        '--bg-tertiary': '#DCDCDC',
        '--border-color': '#C8C8C8',
        '--text-primary': '#011627',
        '--text-secondary': '#4A5568',
        '--accent-primary': '#3C8DBC',
        '--accent-hover': '#2f7096',
        '--accent-text-color': '#FFFFFF',
        '--danger-primary': '#EF5350',
        '--danger-hover': '#d74a47',
    },
    'witchcraft': {
        '--bg-primary': '#1A1225',
        '--bg-secondary': '#251A35',
        '--bg-tertiary': '#302245',
        '--border-color': '#453260',
        '--text-primary': '#E1BEE7',
        '--text-secondary': '#CE93D8',
        '--accent-primary': '#80CBC4',
        '--accent-hover': '#4DB6AC',
        '--accent-text-color': '#1A1225',
        '--danger-primary': '#F06292',
        '--danger-hover': '#E91E63',
    },
};